-- AlterTable
ALTER TABLE "ParkingFloor" ALTER COLUMN "name" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "ParkingLot" ALTER COLUMN "name" SET DATA TYPE VARCHAR(150),
ALTER COLUMN "address" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "PaymentMethod" ALTER COLUMN "cardholderName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "brand" SET DATA TYPE VARCHAR(30),
ALTER COLUMN "last4" SET DATA TYPE VARCHAR(4);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "email" SET DATA TYPE VARCHAR(254),
ALTER COLUMN "firstName" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "lastName" SET DATA TYPE VARCHAR(20);

