steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://spms-backend-397963581210.asia-south1.run.app'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spms-frontend'
      - .
    dir: 'frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spms-frontend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - spms-frontend
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spms-frontend'
      - '--region=asia-south1'
      - '--allow-unauthenticated'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spms-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
