steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spms-backend'
      - .
    dir: 'backend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spms-backend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - spms-backend
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spms-backend'
      - '--region=asia-south1'
      - '--allow-unauthenticated'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spms-backend'

options:
  logging: CLOUD_LOGGING_ONLY
